[package]
name = "motif_finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
log = { version = "0.4", features = ["std", "serde"] }
itertools = "0.10.5"
